# Generated by Django 4.2.9 on 2025-12-24 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callsignal',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='call',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='call',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['caller', 'status'], name='calls_caller__8bffd9_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['receiver', 'status'], name='calls_receive_301de1_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['room_id'], name='calls_room_id_a82e0d_idx'),
        ),
    ]
