# Generated by Django 4.2.9 on 2025-12-29 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0006_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('business', 'Business or Brand'), ('community', 'Community or Public Figure'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('nonprofit', 'Non-Profit Organization'), ('personal', 'Personal Blog'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='pages/profiles/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='pages/covers/')),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'page_followers',
                'ordering': ['-followed_at'],
            },
        ),
        migrations.CreateModel(
            name='PageRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('moderator', 'Moderator')], max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'page_roles',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='groups/covers/'),
        ),
        migrations.AddField(
            model_name='group',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('secret', 'Secret')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=10),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['privacy'], name='groups_privacy_dac40c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['status'], name='group_membe_status_7630e7_idx'),
        ),
        migrations.AddField(
            model_name='pagerole',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='calls.page'),
        ),
        migrations.AddField(
            model_name='pagerole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagefollower',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_followers', to='calls.page'),
        ),
        migrations.AddField(
            model_name='pagefollower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='followers',
            field=models.ManyToManyField(related_name='followed_pages', through='calls.PageFollower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pagerole',
            unique_together={('user', 'page')},
        ),
        migrations.AlterUniqueTogether(
            name='pagefollower',
            unique_together={('user', 'page')},
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['creator'], name='pages_creator_b1c283_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['category'], name='pages_categor_7c9b27_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['name'], name='pages_name_796f7d_idx'),
        ),
    ]
